### ISSUE TITLE
bug in -t option (fails if entry with no first_run date)

### ISSUE THREAD

**Issue by johnmccash** [williballenthin/python-registry#70]
Hey Willi! I just found a bug in amcache.py. I was running it on an Amcache.hve file extracted from a Windows 7 host (I just found out that MS apparently backported whatever change creates this hive to Win7), and I get an error (only) when running it with the -t option.

```
$ python amcache.py  -t Amcache.hve
Traceback (most recent call last):
  File "amcache.py", line 225, in <module>
    main(argv=sys.argv)
  File "amcache.py", line 202, in main
    ts = getattr(e, t)
AttributeError: 'ExecutionEntry' object has no attribute 'first_run'
```

I'm guessing for some reason certain entries don't have one of the timestamp values set... Then again, the first_run time should be the last modified time on the key, right?... Weird.

**Comment by williballenthin** [comment]
bug introduced in dca2953ef54ab51cc6e908893fe42efde8518943 and fixed in 710625b91f1a0322d31dfe65b3467ed308a852c9

thanks for the report @johnmccash!

**Comment by johnmccash** [comment]
NTAC:3NS-20
Actually, that would be @johnmccash2
                John
